BOOK_SUMMARIES = {
  "1984": "Romanul lui George Orwell descrie o societate distopica in care Partidul controleaza totul: istoria este rescrisa, gandurile sunt politiste, iar supravegherea este neintrerupta. Winston Smith incearca sa-si pastreze umanitatea si sa caute adevarul intr-o lume a minciunii institutionalizate. Relatia sa cu Julia devine un act de rezistenta, dar sistemul este nemilos. Cartea mediteaza asupra libertatii, manipularii si fragilitatii individului in fata autoritarismului.",
  "The Hobbit": "Bilbo Baggins, un hobbit comod, este invitat de vrajitorul Gandalf sa se alature unei companii de pitici conduse de Thorin Oakenshield. Scopul lor este recuperarea comorii furate de dragonul Smaug din Muntele Singuratic. In drumul lor, intalnesc troli, elfi, paianjeni uriasi si Gollum, de la care Bilbo gaseste un inel misterios. Bilbo se descopera pe sine ca un erou nestiut, iar povestea pune accent pe curaj, prietenie si depasirea propriilor limite.",
  "Dune": "Pe Arrakis, singura sursa de melanj, Paul Atreides intra intr-un conflict de putere intre mari case nobiliare si Imperiu. Tradarea ii rapeste familia, dar alianta cu Fremenii ii da sansa sa schimbe soarta planetei. Viziunile si instruirea sa il transforma intr-o figura mesianica. Romanul combina politica, ecologie si misticism, explorand pretul puterii si consecintele profetiilor.",
  "Harry Potter and the Sorcerer's Stone": "Harry descopera la 11 ani ca este vrajitor si intra la Hogwarts, unde leaga prietenii cu Ron si Hermione. In timp ce exploreaza scoala, afla despre Piatra Filozofala si despre intoarcerea lui Voldemort. Curajul, loialitatea si ingeniozitatea lor ii ajuta sa protejeze scoala. Cartea vorbeste despre apartenenta, familie aleasa si puterea prieteniei.",
  "To Kill a Mockingbird": "In Alabama anilor 1930, Scout si Jem invata despre nedreptate cand tatal lor, Atticus Finch, apara un barbat de culoare acuzat pe nedrept. Narata cu inocenta, povestea pune in lumina rasismul, empatia si curajul moral. Intalnirea cu Boo Radley le schimba felul de a vedea oamenii ‘diferiti’.",
  "The Alchemist": "Santiago porneste din Spania spre Egipt urmand semnele destinului in cautarea comorii din visele sale. Intalneste personaje-cheie — regele misterios, alchimistul — care il ghideaza spre intelegerea propriei Legende Personale. Calatoria devine una spirituala despre a-ti urma inima si a invata din semnele lumii.",
  "The Book Thief": "Liesel Meminger este adoptata de o familie germana in timpul regimului nazist. Furtul de carti devine modul ei de a face fata pierderilor si violentelor razboiului. Cand familia ascunde un evreu in pivnita, legaturile de prietenie si curajul sunt puse la incercare. Naratiunea, condusa de Moarte, exploreaza puterea cuvintelor de a salva si distruge.",
  "Pride and Prejudice": "Elizabeth Bennet si domnul Darcy trec printr-o suita de neintelegeri si judecati pripite. Intr-o societate ghidata de averi si rang, iubirea lor evolueaza odata cu depasirea mandriei si a prejudecatilor. Romanul ironizeaza moravurile epocii si sustine importanta integritatii si a alegerii personale.",
  "The Name of the Wind": "Kvothe, muzician si magician talentat, isi spune povestea: copilaria in trupa Edema Ruh, tragedia provocata de Chandriani si anii de studiu la Universitate. Obsesia cunoasterii il impinge spre riscuri care ii modeleaza destinul. Cartea exploreaza puterea povestilor, numele lucrurilor si pretul ambitiei.",
  "The Catcher in the Rye": "Holden Caulfield, adolescent de 16 ani, umbla prin New York dupa exmatriculare, dezamagit de ‘falsitatea’ lumii adulte. Isi cauta autenticitatea si protectia pentru inocenta copiilor, simbolizata de dorinta de a fi ‘prinzatorul in lanul de secara’. Un portret memorabil al nelinistii adolescentei.",
  "All the Light We Cannot See": "Marie-Laure, o fata oarba din Franta, si Werner, un baiat german talentat la radio, traiesc destine paralele in timpul razboiului. Drumurile lor se intersecteaza in Saint-Malo, demonstrand cum bunatatea poate razbi in vremuri intunecate. Romanul celebreaza curiozitatea, rezilienta si micile acte de umanitate.",
  "The Fellowship of the Ring": "Frodo Mosneagu mosteneste Inelul Puterii, iar impreuna cu Sam, Merry, Pippin si alti insotitori porneste spre Mordor pentru a-l distruge. Calatoria lor este presarata cu primejdii si sacrificii. Tema centrala: puterea prieteniei si speranta in fata raului."
}
